site_name: FRICOSIPY

theme:
  name: material
  logo: images/FRICOSIPY_Logo.png
  palette:
    primary: "#f7f7f7"   # Light gray header like RTD
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - mkdocs-autorefs
  - markdown-include

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - "The FRICOSIPY Model":
    - Introduction: introduction.md
    - Surface Energy Balance: surface_energy_balance.md
    - Multi-layer Subsurface Model: subsurface_model.md
  - "Getting Started":
    - Installation: installation.md
    - Model Input Files: model_input_files.md
    - Parameters: parameters.md
    - Running a Simulation: running_a_simulation.md
    - Result Viewer: result_viewer.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
