site_name: FRICOSIPY
theme:
  name: readthedocs
  highlightjs: true
  logo: images/FRICOSIPY_Logo.png

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - "The FRICOSIPY Model":
    - Introduction: introduction.md
    - Surface Energy Balance: surface_energy_balance.md
    - Precipitation Model: precipitation_model.md
    - Subsurface Model: subsurface_model.md
  - "Getting Started":
    - Installation: installation.md
    - Model Input Files: model_input_files.md
    - Parameters: parameters.md
    - Running a Simulation: running_a_simulation.md
    - Result Viewer: result_viewer.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
