site_name: FRICOSIPY
site_url: https://fricosipy.readthedocs.io/
site_author: Marcus Alexander Gastaldello
site_description: "The University of Fribourg Variant of the Coupled Snow & Ice Model in Python"

theme:
  name: readthedocs
  highlightjs: true
  logo: images/FRICOSIPY_Logo.png

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - "The FRICOSIPY Model":
    - Introduction: introduction.md
    - Surface Energy Balance: surface_energy_balance.md
    - Multi-layer Subsurface Model: subsurface_model.md
  - "Getting Started":
    - Installation: installation.md
    - Model Input Files: model_input_files.md
    - Parameters: parameters.md
    - Running a Simulation: running_a_simulation.md
    - Result Viewer: result_viewer.md
  
extra:
  extra_head:
    - overrides/meta.html
