site_name: FRICOSIPY
theme:
  name: material
  logo: images/FRICOSIPY_Logo.png
  favicon: images/FRICOSIPY_Logo.png
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'       # similar to Read the Docs default
    code: 'Roboto Mono'  # similar to Read the Docs
  features:
    - navigation.expand        # expand navigation like RTD
    - navigation.tabs          # or remove if you want side nav
    - content.code.copy        # optional, copy code button
    - toc.integrate            # table of contents integrated
extra_css:
  - assets/css/custom.css      # optional: fine-tune spacing/colors

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - "The FRICOSIPY Model":
    - Introduction: introduction.md
    - Surface Energy Balance: surface_energy_balance.md
    - Multi-layer Subsurface Model: subsurface_model.md
  - "Getting Started":
    - Installation: installation.md
    - Model Input Files: model_input_files.md
    - Parameters: parameters.md
    - Running a Simulation: running_a_simulation.md
    - Result Viewer: result_viewer.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
