site_name: FRICOSIPY
site_url: https://fricosipy.readthedocs.io/en/latest/
site_author: Marcus Alexander Gastaldello
site_description: "The University of Fribourg Variant of the Coupled Snow & Ice Model in Python"

theme:
  name: readthedocs
  highlightjs: true
  logo: images/FRICOSIPY-logo-blue.png
  custom_dir: docs/custom_theme

extra:
  favicon: img/favicon_v2.ico
  
plugins:
  - search
  - meta-descriptions
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - "The FRICOSIPY Model":
    - Introduction: introduction.md
    - Surface Energy Balance: surface_energy_balance.md
    - Multi-layer Subsurface Model: subsurface_model.md
  - "Walkthrough":
    - Installation: installation.md
    - Model Input Files: model_input_files.md
    - Parameters: parameters.md
    - Running a Simulation: running_a_simulation.md
    - Result Viewer: result_viewer.md
  - "Advanced":
    - Model Architecture: model_architecture.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
